language: python
python:
    - "2.7"
cache: apt
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends ruby-sass
install:
    - "sudo apt-get install pandoc"  
    - "pip install -r requirements.txt"
    - pip install nose
    - pip install -e git://github.com/getpelican/pelican.git#egg=pelican
    - pip install --use-mirrors Markdown
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors webassets cssmin; fi
script: "pelican content/" 
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sentimentalarse.com
    endpoint: sentimentalarse.com.s3-website-us-east-1.amazonaws.com
    skip_cleanup: true
    local-dir: output
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always
